version: 2

models:
  - name: vw_dim_policy
    description: "object to hold distinct policies"
    schema: "staging"
    columns:
      - name: policy_id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
